name: Android CI

on: 
  release:
    types: [published]
  push:
    tags:
    - '3.*'
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: install git
      run: |
        sudo apt-get update
        sudo apt-get -y install git
    - name: remove 18plus
      run: |
        echo "ojbk">$GITHUB_WORKSPACE/app/src/main/assets/18PlusList.txt
    - name: release apk sign
      run: |
        git clone https://github.com/10bits/gedoor-Build.git /opt/gedoor-Build
        cp /opt/gedoor-Build/.github/workflows/legado.jks $GITHUB_WORKSPACE/app/legado.jks
        sed '$a\RELEASE_STORE_FILE=./legado.jks' $GITHUB_WORKSPACE/gradle.properties -i 
        sed '$a\RELEASE_KEY_ALIAS=legado' $GITHUB_WORKSPACE/gradle.properties -i
        sed '$a\RELEASE_STORE_PASSWORD=gedoor_legado' $GITHUB_WORKSPACE/gradle.properties -i
        sed '$a\RELEASE_KEY_PASSWORD=gedoor_legado' $GITHUB_WORKSPACE/gradle.properties -i
        sed "s/'.release'/'.releaseA'/" $GITHUB_WORKSPACE/app/build.gradle -i
        sed 's/.release/.releaseA/g' $GITHUB_WORKSPACE/app/google-services.json -i
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease 
        mkdir /opt/build
        cp -r $GITHUB_WORKSPACE/app/build/outputs/apk/app/release /opt/build
    - name : upload apk
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: legado apk
        path: /opt/build/release
